# This workflow will install backend's requirements and run tests

name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Compose
        run: docker compose build

      - name: Run Docker Compose
        run: docker compose up -d

      - name: Wait a bit for MySQL to boot
        run: sleep 10

      - name: Install deps
        run: docker compose exec web bash -c "make -f Makefile-docker update_deps"

      - name: Patch Django
        run: docker compose exec web bash -c "sed -i 's/TX_ISOLATION = /transaction_isolation = /' /usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py"

      - name: Run tests
        run: docker compose exec web bash -c 'python -m pytest --junitxml=src/test_report36.xml -m "not es_tests" src/olympia/'

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Python 3.6 Test Results"
          files: src/test_report36.xml